# Project Configuration for Quaint-App
# This configuration is designed for a single Docker container deployment on Jetson.
# Paths are relative to the container's /app directory.

model_settings:
  local_llm_path: "/app/models" # Path to specialized local LLMs (e.g., for perception)
  embedding_model_name: "all-MiniLM-L6-v2" # Sentence Transformer model for embeddings
  gemini_api_key: "YOUR_GEMINI_API_KEY" # Placeholder: Use environment variable in production

data_settings:
  raw_text_dir: "/app/data/raw/texts" # Path to raw text data within the container
  raw_pdf_dir: "/app/data/raw/pdfs"   # Path to raw PDF data within the container
  rag_chunk_size: 500
  rag_chunk_overlap: 50
  rag_top_k: 5 # Number of top results to retrieve from CortexDB for RAG

vector_db_settings:
  chromadb_path: "/app/vector_db/cortexdb_data" # Path for CortexDB persistence within the container
  collection_name: "enterprise_knowledge_base"